name: My Template
description: This is my GitHub template.

parameters:
  package_name:
    description: The name of the new package.
    required: true

actions:
  - name: Replace package name
    description: Replace the package name in the template files.
    uses: ahmadawais/repo-name@v1
    with:
      package_name: ${{ parameters.package_name }}
